name: Trigger Periodic Netlify Build
on:
  schedule:
    # Run at 01 hour, on the first every 3 months
    - cron: '* 1 1 */3 *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ee22aa93aee2aa054e2093e
