name: Trigger Periodic Netlify Build
on:
  schedule:
    - cron: '10 1 17 */1 *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ee22aa93aee2aa054e2093e
